workflows:
  build-apk:
    name: Build APK
    environment:
      flutter: stable
    scripts:
      - echo "Unzipping project"
      - unzip app.zip
      - echo "Entering project folder"
      - cd */ 
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
